# Creating Functions

## Combining Functions

“Adding” two strings produces their concatenation: 'a' + 'b' is 'ab'. Write a function called fence that takes two parameters called original and wrapper and returns a new string that has the wrapper character at the beginning and end of the original. A call to your function should look like this:

In [6]:
def fence(original, wrapper):
    return(wrapper + original + wrapper)

In [7]:
fence("name", "*")

'*name*'

## Return vs. Print

Note that return and print are not interchangeable. print is a Python function that prints data to the screen. It enables us, users, see the data. return statement, on the other hand, makes data visible to the program. Let’s have a look at the following function:

In [9]:
def add(a, b):
    print(a + b)

**Question**: What will we see if we execute the following commands?

In [10]:
A = add(7, 3)
print(A)

10
None


The first line will execute the function, which will print the result `a+b`. The second line will return nothing, because nothing is returned from the function, so nothing is assigned to the variable `A`

## Selecting Characters From Strings

If the variable s refers to a string, then `s[0]` is the string’s first character and `s[-1]` is its last. Write a function called `outer` that returns a string made up of just the first and last characters of its input. 

In [12]:
def outer(string):
    return(string[0] + string[-1])

outer("Test")

'Tt'

## Rescalling an array

Write a function `rescale` that takes an array as input and returns a corresponding array of values scaled to lie in the range 0.0 to 1.0. (Hint: If L and H are the lowest and highest values in the original array, then the replacement for a value v should be (v-L) / (H-L).)

In [60]:
import numpy
def rescale(input_data):
    # Get largest value:
    max_value = numpy.max(input_data)
    # Get smallest value:
    min_value = numpy.min(input_data)
    # Calculate output
    output_data = (input_data - min_value)/(max_value - min_value)
    
    return(output_data)

in_array = numpy.array([[1, 2], [6, 3]])
out_array = rescale(in_array)

print("Original array:")
display(in_array)
print("Rescaled array:")
display(out_array)

Original array:


array([[1, 2],
       [6, 3]])

Rescaled array:


array([[0. , 0.2],
       [1. , 0.4]])

## Testing and Documenting Your Function

Run the commands help(numpy.arange) and help(numpy.linspace) to see how to use these functions to generate regularly-spaced values, then use those values to test your rescale function. Once you’ve successfully tested your function, add a docstring that explains what it does.

Testing my function:

In [61]:
## Create 5 equally spaced numbers.
test_array = numpy.linspace(4,10, num=5)
## When rescaled, should return 0, 0.25, 0.5, 0.75, 1:
rescale(test_array)
## SUCCESS!

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

Adding a docstring to my function.

In [66]:
def rescale(input_data):
    '''This function takes an array and returns a new array of same dimensions with rescaled values. 
    The new array will have values between 0 and 1 spaced in the same way as the input array.
    
    Examples:
    
    >>> ## Create 5 equally spaced numbers.
    >>> test_array = numpy.linspace(4,10, num=5)
    >>> ## When rescaled, should return 0, 0.25, 0.5, 0.75, 1:
    >>> rescale(test_array)
    array([0.  , 0.25, 0.5 , 0.75, 1.  ])
    '''
    # Get largest value:
    max_value = numpy.max(input_data)
    # Get smallest value:
    min_value = numpy.min(input_data)
    # Calculate output
    output_data = (input_data - min_value)/(max_value - min_value)
    
    return(output_data)

In [67]:
help(rescale)

Help on function rescale in module __main__:

rescale(input_data)
    This function takes an array and returns a new array of same dimensions with rescaled values. 
    The new array will have values between 0 and 1 spaced in the same way as the input array.
    
    Examples:
    
    >>> ## Create 5 equally spaced numbers.
    >>> test_array = numpy.linspace(4,10, num=5)
    >>> ## When rescaled, should return 0, 0.25, 0.5, 0.75, 1:
    >>> rescale(test_array)
    array([0.  , 0.25, 0.5 , 0.75, 1.  ])



## Defining Defaults

Rewrite the rescale function so that it scales data to lie between 0.0 and 1.0 by default, but will allow the caller to specify lower and upper bounds if they want.

In [75]:
def rescale(input_data, interval = (0, 1)):
    '''Rescales values to be within interval'''
    min_value = numpy.min(input_data)
    max_value = numpy.max(input_data)
    output_data = interval[0] + (input_data - min_value)/(max_value - min_value)*(interval[1] - interval[0])
    return(output_data)

In [76]:
rescale(test_array, interval = (-1,1))

array([-1. , -0.5,  0. ,  0.5,  1. ])

## Variables inside and outside functions

**Q**: What does the following piece of code display when run - and why?

**A**: This code will return 8, 41, and 32 fahrenheit converted to kelvin, and finally 0. The variable `k` is not changed outside the scope of the function, so it will still be zero.

In [82]:
f = 0
k = 0

def f2k(f):
  k = ((f-32)*(5.0/9.0)) + 273.15
  return k

print(f2k(8))
print(f2k(41))
print(f2k(32))

print(k)

259.81666666666666
278.15
273.15
0


## Mixing Default and Non-Default Parameters

The following code will return in the output `SyntaxError`. This is because the variable `one` and `three` are not given default values, while `two` is. `one` and `three` should be defined first for this to work.

In [87]:
def numbers(one, two=2, three, four=4):
    n = str(one) + str(two) + str(three) + str(four)
    return n

print(numbers(1, three=3))

SyntaxError: non-default argument follows default argument (<ipython-input-87-28e3d1a5100b>, line 1)

The following code will work just fine, since all variables without default values are put first in the function definition.

In [88]:
def func(a, b=3, c=6):
  print('a: ', a, 'b: ', b, 'c:', c)

func(-1, 2)

a:  -1 b:  2 c: 6


## The Old Switcheroo

The code below will print `3 7` since the function doesn't print or return anything.

In [89]:
a = 3
b = 7

def swap(a, b):
    temp = a
    a = b
    b = temp

swap(a, b)

print(a, b)

3 7
